version: '3'

services:
  redis:
    image: redis
    networks:
      - lto

  anchor:
    container_name: anchor
    image: legalthings/anchor
    environment:
      - LTO_API_KEY=<a secret to use the api>
    ports:
      - 80:80
    networks:
      - lto
    depends_on:
      - redis
      - public-node

  public-node:
    container_name: public-node
    image: legalthings/public-node
    environment:
      - LTO_WALLET_SEED=<seed of your wallet>
      - LTO_WALLET_PASSWORD=<a password for your wallet>
      - LTO_API_KEY=<a secret to use the api>
    networks:
      - lto

networks:
  lto:
    driver: bridge





